### ISSUE TITLE
compatibility to markdown<3.5?

### ISSUE THREAD

**Issue by arian-f** [jambonrose/markdown_subscript_extension#65]
currently markdown_subscript is marked compatible to

`Markdown<3.1,>=2.5`

with current markdown version 3.4.1 - could you check whether it's compatible and bump the compatibility to 3.5 if possible?

**Comment by fmatter** [comment]
Funny, I just came here to discuss exactly this issue (in an otherwise not too active repo). Using it with `3.4.1` gives me

` extendMarkdown() missing 1 required positional argument: 'md_globals'`

**Comment by fmatter** [comment]
Oh, and this was addressed (in the form of taking care of deprecation warnings) in #64. However, there are more errors:

`AttributeError: 'Registry' object has no attribute 'add'`

**Comment by fmatter** [comment]
@jambonrose are you interested in bringing this extension up to speed with the current extension API of python-markdown?

**Comment by fmatter** [comment]
I tried following [this extensions API example](https://python-markdown.github.io/extensions/api/#example_3) and got the following code to work with `3.4.1`:

```
class SubscriptProcessor(InlineProcessor):
    def handleMatch(self, m, data):
        el = etree.Element('sub')
        el.text = m.group(1)
        return el, m.start(0), m.end(0)

class SubscriptExtension(Extension):
    """Extension: text between ~ characters will be subscripted."""
    def extendMarkdown(self, md):
        SUB_PATTERN = r'~(.*?)~'  # like ~sub~
        md.inlinePatterns.register(SubscriptProcessor(SUB_PATTERN, md), "sub", 175)
```

However, this solution leaves out the [relative order](https://github.com/jambonrose/markdown_subscript_extension/blob/development/mdx_subscript.py#L34) to the `not_strong` pattern (I found nothing on specifying the relative order of extensions, or what the `not_strong` pattern even is).

Also, you might just want to install [PyMdown Extensions](https://facelessuser.github.io/pymdown-extensions/) and then use `extensions=["pymdownx.tilde"]`.
